# Site settings
title: "| Timothy Hsieh |"
description: "Back-End Engineer | Educator"
url: 'https://timothyhsieh27.github.io/'

resume: 'https://drive.google.com/file/d/0B-IZ085vX9wkOEVmQllRUHlCcTg/view'

author:
  name: 'Timothy Hsieh'
  email: timothyhsieh27@gmail.com
  twitter_username: damienjames27
  github_username:  timothyhsieh27
  linkedin_username:  timothyhsieh27

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
